import { useState } from 'react';
import { X, Code2, AlertTriangle, Play } from 'lucide-react';
import useStore from '../store/store';
import './ImportCodeStepsModal.css';

export default function ImportCodeStepsModal() {
  const closeModal = useStore((s) => s.closeModal);
  const showToast = useStore((s) => s.showToast);
  const currentConfig = useStore((s) => s.currentConfig);
  const updateConfig = useStore((s) => s.updateConfig);

  const [jsonInput, setJsonInput] = useState('');
  const [error, setError] = useState(null);

  const handleImport = () => {
    try {
      if (!jsonInput.trim()) {
        throw new Error('Input is empty');
      }

      const parsed = JSON.parse(jsonInput);
      
      if (!Array.isArray(parsed)) {
        throw new Error('Input must be a JSON array of step objects');
      }

      // Format steps with required IDs if missing
      const formattedSteps = parsed.map(step => ({
        ...step,
        id: step.id || crypto.randomUUID(),
        enabled: step.enabled !== undefined ? step.enabled : true,
        type: step.type || 'pick',
        label: step.label || 'Imported Step'
      }));

      // Append steps
      const currentSteps = currentConfig?.steps || [];
      const newSteps = [...currentSteps, ...formattedSteps];

      updateConfig({ steps: newSteps });
      showToast(`Successfully imported ${formattedSteps.length} step(s)`, 'success');
      closeModal();
    } catch (err) {
      setError(err.message);
    }
  };

  const loadExample = () => {
    const example = [
      {
        "type": "pick",
        "label": "Pick Component",
        "dimensionRef": "paste-dimension-id-here"
      },
      {
        "type": "generative",
        "label": "Draft Email",
        "generativeInstruction": "Write a short email based on the component."
      }
    ];
    setJsonInput(JSON.stringify(example, null, 2));
    setError(null);
  };

  return (
    <div className="modal-overlay" onClick={closeModal}>
      <div className="modal code-steps-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Import Code Steps</h2>
          <button className="btn-icon" onClick={closeModal}>
            <X size={16} />
          </button>
        </div>
        
        <div className="modal-body">
          <p className="text-muted mb-md">
            Paste a JSON array of step objects to instantly construct large step definitions. This is ideal for importing configurations generated by LLMs.
          </p>
          
          <div className="code-input-wrapper">
            <textarea
              className="code-textarea"
              placeholder="[\n  {\n    &#34;type&#34;: &#34;pick&#34;,\n    &#34;label&#34;: &#34;My Step&#34;\n  }\n]"
              value={jsonInput}
              onChange={(e) => {
                setJsonInput(e.target.value);
                if (error) setError(null);
              }}
              spellCheck={false}
            />
          </div>

          {error && (
            <div className="error-banner">
              <AlertTriangle size={14} />
              <span>{error}</span>
            </div>
          )}
        </div>

        <div className="modal-footer footer-spaced">
          <button type="button" className="btn btn-outline" onClick={loadExample}>
            <Code2 size={14} />
            Load Example JSON
          </button>
          
          <div style={{ display: 'flex', gap: '8px' }}>
            <button type="button" className="btn" onClick={closeModal}>
              Cancel
            </button>
            <button type="button" className="btn btn-primary" onClick={handleImport}>
              <Play size={14} />
              Import Steps
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
